apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: quarkus
    appstudio.openshift.io/component: devfile-sample-code-with-quarkus-8xck
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-8xck
  namespace: e2e-demos-iyma-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_devfile-samples_devfile-sample-code-with-quarkus
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
